schema_version: 1

context:
  name: mlx-vlm
  version: 0.7.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mlx_vlm-${{ version }}.tar.gz
  sha256: 0bfc3ae1f82cb0a7866bf9f1257d672f6450c5fbd13f22b2d62fddb72b759379

build:
  number: 0
  noarch: python
  script:
    - sed -i 's/opencv-python>=4.12.0.88/opencv-python>=4.12/g' requirements.txt
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - sed
  run:
    - python >=${{ python_min }}
    - mlx >=0.32.2
    - tqdm >=4.66.2
    - transformers >=5.14.0
    - pillow >=10.3.0
    - requests >=2.31.0
    - fastapi >=0.95.1
    - numpy
    - uvicorn
    - miniaudio >=1.59
    - opencv >=4.12.0.88
    - mlx-audio >=0.4.8
    - llguidance >=1.7.0
    - starlette >=1.0.1
    - python-multipart >=0.0.9
    - websockets >=14.0
    - sentencepiece >=0.2.0
    - jinja2 >=3.1.0
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - mlx_vlm

about:
  summary: Vision LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Blaizzy/mlx-vlm

extra:
  recipe-maintainers:
    - xhochy
